### PR TITLE
375 vote subsidy metamask

### LINKED ISSUE #375: Vote subsidy is not working after creating user via Metamask.
This is a known issue. Vote subsidy is not working and account begins experience with 0 votes. I think this has to do with the only `Promise` in the code which is not compatible with the `meteor` model. 

screenshot 2018-07-16 18 11 58

### PR DESCRIPTION
**Pull request by medied**
Left in-line comments, please address to understand if it makes sense to merge this PR as is.

Closes #375. Also this PR touches the Wallet schema so it's represents initial steps towards closing #370.

### CODE REVIEW

File: imports/api/blockchain/modules/web3Util.js [hunk 1]
```diff
@@ -0,0 +1,33 @@
+import Web3 from 'web3';
```
Comment (medied) [inline imports/api/blockchain/modules/web3Util.js]: Looking for feedback if /imports/api/blockchain/modules/ is a good place for this sort of new file

File: imports/api/transactions/transaction.js [hunk 2]
```diff
@@ -814,6 +815,25 @@ const _genesisTransaction = (userId) => {
   _transact(Meteor.settings.public.Collective._id, userId, rules.VOTES_INITIAL_QUANTITY);
 };
 
+/**
+* @summary reads balance from publicAddress and loads it into user wallet
+* @param {string} userId - id of user being generated within collective
+*/
+const _loadExternalCryptoBalance = (userId) => {
```
Comment (medied) [inline imports/api/transactions/transaction.js]: One decision being made with this PR would be modularizing the initial balance loading into this new method (and hence different than _genesisTransaction()). Because the way Metamask users are being created within the app is different than regular users, I'm thinking it makes sense to have this separate method for balance loading. This is also looking into the future, thinking it would add more flexibility when the time comes where this sort of feature will be needed for all users.

Also with this PR the wallet.available variable is being reset every time a user logs in, leaving it as such for testing purposes for now. This is where the daemon would come in and keep numbers in sync.

File: imports/api/transactions/transaction.js [hunk 3]
```diff
@@ -814,6 +815,25 @@ const _genesisTransaction = (userId) => {
...
+  const user = Meteor.users.findOne({ _id: userId });
+  if (user.services.metamask != null){
+    user.profile.wallet = _generateWalletAddress(user.profile.wallet);
+    let publicAddress = user.services.metamask.publicAddress
+    let weiBalance = getWeiBalance(publicAddress);
+    
+    user.profile.wallet.currency = 'WEI';
+    user.profile.wallet.balance = weiBalance.toNumber();
```
Comment (medied) [inline imports/api/transactions/transaction.js]: The wallet schema is still expecting numbers. The way I'm thinking about this is that we handle crypto balances in `bigNumbers` for all math operations and convert `toNumber()` only when needed like here. Less than ideal but it seems it's the [current state of handling this issue](https://hackernoon.com/a-note-on-numbers-in-ethereum-and-javascript-3e6ac3b2fad9)

File: imports/api/blockchain/modules/web3Util.js (hunk 1 above)
Comment (santisiri) [reply imports/api/blockchain/modules/web3Util.js]: Looks good for me, as long as it properly works.

File: imports/startup/both/modules/metamask.js [hunk 4]
```diff
@@ -82,11 +82,6 @@ if (Meteor.isClient) {
             })
           }
         });
-        Meteor.call('subsidizeUser', (subsidyError) => {
```
[the remark this answers is not in the document]
Comment (santisiri) [reply imports/startup/both/modules/metamask.js]: Just noticed its metamask. All fine.

File: imports/api/users/Wallet.js [hunk 5]
```diff
@@ -17,7 +17,7 @@ Schema.Wallet = new SimpleSchema({
   },
   currency: {
     type: String,
-    allowedValues: ['BITCOIN', 'SATOSHI', 'VOTES'],
+    allowedValues: ['BITCOIN', 'SATOSHI', 'VOTES', 'ETH', 'WEI'],
```
[the remark this answers is not in the document]
Comment (medied) [reply imports/api/users/Wallet.js]: Looks like `allowedValues` can be set to a function now ([one](https://github.com/aldeed/meteor-simple-schema/issues/456) [two](https://github.com/aldeed/simple-schema-js#allowedvalues)), so something to explore
